### ISSUE TITLE
How do I remove mending book from trade?

### ISSUE THREAD

**Issue by yashendra2797** [jacky8399/BalancedVillagerTrades#1]
```
remove-mending-trade:
  desc: Removes mending books
  when:
    villager: profession = LIBRARIAN
    result:
      matches:
        - type matches ^mending_$
  do:
    remove: true
```

I dont think this works because mending books are just enchanted books with NBT tags. Any idea on how to remove mending books from being traded?
