### ISSUE TITLE
wandering trader trades are ignoring all rules

### ISSUE THREAD

**Issue by pjindras** [jacky8399/BalancedVillagerTrades#16]
Hi, I wanted to globally disable some trades, for example:

```
dirtfix1:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: dirt
  do:
    remove: true
dirtfix2:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: coarse_dirt
  do:
    remove: true
dirtfix3:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: dirt_path
  do:
    remove: true
dirtfix4:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: rooted_dirt
  do:
    remove: true
dirtfix5:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: Grass_block
  do:
    remove: true
podzolfix1:
  desc: Nerf diamond armor and tool trades
  enabled: true
  when:
    result.type: Podzol
  do:
    remove: true
```

but wandering trader is ignoring all those rules, is it a bug?
I have skyblock server, so I need to re-balance a lot of the vanilla trades to keep the game attractive.

Thank you!

**Comment by jacky8399** [comment]
All recipes should now apply to wandering traders in beta11. In this case, you can just add a check for wandering traders as such:
```yml
podzolfix1:
  enabled: true
  when:
    result.type: podzol
    merchant-type: wandering-trader # <---
  do:
    remove: true
```
