### ISSUE TITLE
Setting a cost type of emerald_block instead of emerald itself

### ISSUE THREAD

**Issue by johnwm47** [jacky8399/BalancedVillagerTrades#3]
Hi there,
Saw your latest commit with the beta function to reroll higher priced books and use blocks instead of the capped stack of 64 emeralds. 
I was trying to tweak this to be able to change the price of a mending book from emeralds to emerald blocks. Is this possible currently? Can't figure out how to do this if so, and if not it is a feature I'd love to see. Here is my poor attempt at implementing in the recipe.

```adjust-mending-books:
    desc: Adjusts mending book trades
    when:
        villager: profession = LIBRARIAN
        result:
            matches:
              - type = enchanted_book
              - enchantments contains mending
    do:
       set:
        ingredient-0: amount>=25
        ingredient-0: type = "emerald_block"

**Comment by jacky8399** [comment]
To modify the trades, you have to change their fields.
See https://github.com/jacky8399/BalancedVillagerTrades/wiki/Fields
```yaml
    desc: Adjusts mending book trades
    when:
        villager:
          profession: LIBRARIAN
        result:
          type: "minecraft:enchanted_book"
          enchantments: contains minecraft:mending
    do:
       set:
        ingredient-0:
          amount: '>= 25' # Sets the amount of ingredient 0 to be >= 25
          type: "emerald_block" # Sets the type of ingredient 0 to emerald block
```
