### ISSUE TITLE
Question: How to randomly apply 'Vanishing Curse' on trade item?

### ISSUE THREAD

**Issue by TetraTheta** [jacky8399/BalancedVillagerTrades#9]
I want to randomly apply Vanishing Curse enchantment to diamond item trade result of Armorer or Toolsmith.
```yaml
diamond-item-trades:
  desc: Nerf diamond armor and tool trades by damaging them slightly and randomly apply vanishing curse
  enabled: true
  when:
    villager.profession: matches ^armorer|toolsmith$
    result.type: contains diamond_
  do:
    set:
      apply-discounts: false
      max-uses: 1
      result.damage: 100
      lua: |-
          result_item = trade.result
          seed = math.random()
          if (seed % 2 == 0) then
              result_item.enchantments.vanishing_curse = 1
          end
```
> random part is not good because I can't use `os.time()` for seed of `math.random()`

But after I load up server, I met this error message.
```
[13:40:53 WARN]: [BalancedVillagerTrades] root(EmptyFieldProxy{field=trade}) does not have field lua! Skipping.
```
Other `set`s are correctly implemented, like they don't get discounted, the trade's max uses is once, the result diamond items are damaged etc. Only `lua` part is ignored.

This implies I've done something wrong about lua. I want to fix it, but don't know how.

**Comment by jacky8399** [comment]
`lua` is an action, so it needs to be on the same level as `set`.
```yaml
diamond-item-trades:
  desc: Nerf diamond armor and tool trades by damaging them slightly and randomly apply vanishing curse
  enabled: true
  when:
    villager.profession: matches ^armorer|toolsmith$
    result.type: contains diamond_
  do:
    set:
      apply-discounts: false
      max-uses: 1
      result.damage: 100
    # Notice the indentation
    lua: |-
        result_item = trade.result
        seed = math.random()
        if (seed % 2 == 0) then
            result_item.enchantments.vanishing_curse = 1
        end
```
As for `os.time()`, I will see if I can remove some of the dangerous methods from `os` first.

**Comment by TetraTheta** [comment]
I updated my code with correct indentation.
```yaml
diamond-item-trades:
  desc: Nerf diamond armor and tool trades by damaging them slightly and randomly apply vanishing curse
  enabled: true
  when:
    villager.profession: matches ^armorer|toolsmith$
    result.type: contains diamond_
  do:
    set:
      apply-discounts: false
      max-uses: 1
      result.damage: 100
  lua: |-
    result_item = trade.result
    seed = math.floor((math.random() * 100) + 0.5)
    if (seed % 2 == 0) then
        result_item.enchantments.vanishing_curse = 1
    end
```
But I'm not sure if `result_item.enchantments.vanishing_curse = 1` is right code or not, because I don't see any 'Vanishing Curse' enchantment is applied to villager trade.

**Comment by jacky8399** [comment]
A bug in v2.0-beta7 prevented enchantments with underscores to be changed. Since the next version is not quite ready yet, I've built a beta8 JAR that includes the fix. I've tested your recipe with the jar and it seems to work, so if you encounter any issues feel free to comment again.

[BalancedVillagerTrades-2.0-beta8-enchantments-fix.zip](https://github.com/jacky8399/BalancedVillagerTrades/files/11899041/BalancedVillagerTrades-2.0-beta8-enchantments-fix.zip)

And there are some issues with your recipe. The indentation is still incorrect, and the `lua` block is still not on the same level as the `set` block. Additionally, since all recipes will run whenever a player interacts with a villager, your Lua script will run every time and all diamond tools will eventually have Curse of Vanishing. To fix this, include the undocumented (!) field `is-new` in your `when` block.

The correct recipe should be like this:
```yaml
diamond-item-trades:
  desc: Nerf diamond armor and tool trades by damaging them slightly and randomly apply vanishing curse
  enabled: true
  when:
    villager.profession: matches ^armorer|toolsmith$
    result.type: contains diamond_
    is-new: true # prevents the Lua script from being run again
  do:
#### 4 spaces
    set:
      apply-discounts: false
      max-uses: 1
      result.damage: 100
#### 4 spaces
    lua: |-
      result_item = trade.result
      seed = math.floor((math.random() * 100) + 0.5)
      if (seed % 2 == 0) then
        result_item.enchantments.vanishing_curse = 1
      end
```
